<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<title>Apache Portable Runtime: apr_version.h Source File</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<!-- Generated by Doxygen 1.6.3 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul>
      <li><a href="index.html"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.html"><span>Related&nbsp;Pages</span></a></li>
      <li><a href="modules.html"><span>Modules</span></a></li>
      <li><a href="annotated.html"><span>Data&nbsp;Structures</span></a></li>
      <li class="current"><a href="files.html"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <img id="MSearchSelect" src="search/search.png"
             onmouseover="return searchBox.OnSearchSelectShow()"
             onmouseout="return searchBox.OnSearchSelectHide()"
             alt=""/>
        <input type="text" id="MSearchField" value="Search" accesskey="S"
             onfocus="searchBox.OnSearchFieldFocus(true)" 
             onblur="searchBox.OnSearchFieldFocus(false)" 
             onkeyup="searchBox.OnSearchFieldChange(event)"/>
        <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs">
    <ul>
      <li><a href="files.html"><span>File&nbsp;List</span></a></li>
      <li><a href="globals.html"><span>Globals</span></a></li>
    </ul>
  </div>
<h1>apr_version.h</h1><a href="apr__version_8h.html">Go to the documentation of this file.</a><div class="fragment"><pre class="fragment"><a name="l00001"></a>00001 <span class="comment">/* Licensed to the Apache Software Foundation (ASF) under one or more</span>
<a name="l00002"></a>00002 <span class="comment"> * contributor license agreements.  See the NOTICE file distributed with</span>
<a name="l00003"></a>00003 <span class="comment"> * this work for additional information regarding copyright ownership.</span>
<a name="l00004"></a>00004 <span class="comment"> * The ASF licenses this file to You under the Apache License, Version 2.0</span>
<a name="l00005"></a>00005 <span class="comment"> * (the &quot;License&quot;); you may not use this file except in compliance with</span>
<a name="l00006"></a>00006 <span class="comment"> * the License.  You may obtain a copy of the License at</span>
<a name="l00007"></a>00007 <span class="comment"> *</span>
<a name="l00008"></a>00008 <span class="comment"> *     http://www.apache.org/licenses/LICENSE-2.0</span>
<a name="l00009"></a>00009 <span class="comment"> *</span>
<a name="l00010"></a>00010 <span class="comment"> * Unless required by applicable law or agreed to in writing, software</span>
<a name="l00011"></a>00011 <span class="comment"> * distributed under the License is distributed on an &quot;AS IS&quot; BASIS,</span>
<a name="l00012"></a>00012 <span class="comment"> * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.</span>
<a name="l00013"></a>00013 <span class="comment"> * See the License for the specific language governing permissions and</span>
<a name="l00014"></a>00014 <span class="comment"> * limitations under the License.</span>
<a name="l00015"></a>00015 <span class="comment"> */</span>
<a name="l00016"></a>00016 
<a name="l00017"></a>00017 <span class="preprocessor">#ifndef APR_VERSION_H</span>
<a name="l00018"></a>00018 <span class="preprocessor"></span><span class="preprocessor">#define APR_VERSION_H</span>
<a name="l00019"></a>00019 <span class="preprocessor"></span><span class="comment"></span>
<a name="l00020"></a>00020 <span class="comment">/**</span>
<a name="l00021"></a>00021 <span class="comment"> * @file apr_version.h</span>
<a name="l00022"></a>00022 <span class="comment"> * @brief APR Versioning Interface</span>
<a name="l00023"></a>00023 <span class="comment"> * </span>
<a name="l00024"></a>00024 <span class="comment"> * APR&#39;s Version</span>
<a name="l00025"></a>00025 <span class="comment"> *</span>
<a name="l00026"></a>00026 <span class="comment"> * There are several different mechanisms for accessing the version. There</span>
<a name="l00027"></a>00027 <span class="comment"> * is a string form, and a set of numbers; in addition, there are constants</span>
<a name="l00028"></a>00028 <span class="comment"> * which can be compiled into your application, and you can query the library</span>
<a name="l00029"></a>00029 <span class="comment"> * being used for its actual version.</span>
<a name="l00030"></a>00030 <span class="comment"> *</span>
<a name="l00031"></a>00031 <span class="comment"> * Note that it is possible for an application to detect that it has been</span>
<a name="l00032"></a>00032 <span class="comment"> * compiled against a different version of APR by use of the compile-time</span>
<a name="l00033"></a>00033 <span class="comment"> * constants and the use of the run-time query function.</span>
<a name="l00034"></a>00034 <span class="comment"> *</span>
<a name="l00035"></a>00035 <span class="comment"> * APR version numbering follows the guidelines specified in:</span>
<a name="l00036"></a>00036 <span class="comment"> *</span>
<a name="l00037"></a>00037 <span class="comment"> *     http://apr.apache.org/versioning.html</span>
<a name="l00038"></a>00038 <span class="comment"> */</span>
<a name="l00039"></a>00039 
<a name="l00040"></a>00040 
<a name="l00041"></a>00041 <span class="comment">/* The numeric compile-time version constants. These constants are the</span>
<a name="l00042"></a>00042 <span class="comment"> * authoritative version numbers for APR. </span>
<a name="l00043"></a>00043 <span class="comment"> */</span>
<a name="l00044"></a>00044 <span class="comment"></span>
<a name="l00045"></a>00045 <span class="comment">/** major version </span>
<a name="l00046"></a>00046 <span class="comment"> * Major API changes that could cause compatibility problems for older</span>
<a name="l00047"></a>00047 <span class="comment"> * programs such as structure size changes.  No binary compatibility is</span>
<a name="l00048"></a>00048 <span class="comment"> * possible across a change in the major version.</span>
<a name="l00049"></a>00049 <span class="comment"> */</span>
<a name="l00050"></a><a class="code" href="apr__version_8h.html#a09ffaed0dcb07c22aa5a0efbc41043c2">00050</a> <span class="preprocessor">#define APR_MAJOR_VERSION       1</span>
<a name="l00051"></a>00051 <span class="preprocessor"></span><span class="comment"></span>
<a name="l00052"></a>00052 <span class="comment">/** minor version</span>
<a name="l00053"></a>00053 <span class="comment"> * Minor API changes that do not cause binary compatibility problems.</span>
<a name="l00054"></a>00054 <span class="comment"> * Reset to 0 when upgrading APR_MAJOR_VERSION</span>
<a name="l00055"></a>00055 <span class="comment"> */</span>
<a name="l00056"></a><a class="code" href="apr__version_8h.html#a9470ed7888fcc5637eaf0291a324fcde">00056</a> <span class="preprocessor">#define APR_MINOR_VERSION       3</span>
<a name="l00057"></a>00057 <span class="preprocessor"></span><span class="comment"></span>
<a name="l00058"></a>00058 <span class="comment">/** patch level </span>
<a name="l00059"></a>00059 <span class="comment"> * The Patch Level never includes API changes, simply bug fixes.</span>
<a name="l00060"></a>00060 <span class="comment"> * Reset to 0 when upgrading APR_MINOR_VERSION</span>
<a name="l00061"></a>00061 <span class="comment"> */</span>
<a name="l00062"></a><a class="code" href="apr__version_8h.html#a8c8c1cbf8000059090ba4ac4365eda7d">00062</a> <span class="preprocessor">#define APR_PATCH_VERSION       8</span>
<a name="l00063"></a>00063 <span class="preprocessor"></span><span class="comment"></span>
<a name="l00064"></a>00064 <span class="comment">/** </span>
<a name="l00065"></a>00065 <span class="comment"> * The symbol APR_IS_DEV_VERSION is only defined for internal,</span>
<a name="l00066"></a>00066 <span class="comment"> * &quot;development&quot; copies of APR.  It is undefined for released versions</span>
<a name="l00067"></a>00067 <span class="comment"> * of APR.</span>
<a name="l00068"></a>00068 <span class="comment"> */</span>
<a name="l00069"></a>00069 <span class="comment">/* #undef APR_IS_DEV_VERSION */</span>
<a name="l00070"></a>00070 <span class="comment"></span>
<a name="l00071"></a>00071 <span class="comment">/**</span>
<a name="l00072"></a>00072 <span class="comment"> * Check at compile time if the APR version is at least a certain</span>
<a name="l00073"></a>00073 <span class="comment"> * level.</span>
<a name="l00074"></a>00074 <span class="comment"> * @param major The major version component of the version checked</span>
<a name="l00075"></a>00075 <span class="comment"> * for (e.g., the &quot;1&quot; of &quot;1.3.0&quot;).</span>
<a name="l00076"></a>00076 <span class="comment"> * @param minor The minor version component of the version checked</span>
<a name="l00077"></a>00077 <span class="comment"> * for (e.g., the &quot;3&quot; of &quot;1.3.0&quot;).</span>
<a name="l00078"></a>00078 <span class="comment"> * @param patch The patch level component of the version checked</span>
<a name="l00079"></a>00079 <span class="comment"> * for (e.g., the &quot;0&quot; of &quot;1.3.0&quot;).</span>
<a name="l00080"></a>00080 <span class="comment"> * @remark This macro is available with APR versions starting with</span>
<a name="l00081"></a>00081 <span class="comment"> * 1.3.0.</span>
<a name="l00082"></a>00082 <span class="comment"> */</span>
<a name="l00083"></a><a class="code" href="apr__version_8h.html#ac0646746397b0cb17a6d88ce55558fed">00083</a> <span class="preprocessor">#define APR_VERSION_AT_LEAST(major,minor,patch)                    \</span>
<a name="l00084"></a>00084 <span class="preprocessor">(((major) &lt; APR_MAJOR_VERSION)                                     \</span>
<a name="l00085"></a>00085 <span class="preprocessor"> || ((major) == APR_MAJOR_VERSION &amp;&amp; (minor) &lt; APR_MINOR_VERSION) \</span>
<a name="l00086"></a>00086 <span class="preprocessor"> || ((major) == APR_MAJOR_VERSION &amp;&amp; (minor) == APR_MINOR_VERSION &amp;&amp; (patch) &lt;= APR_PATCH_VERSION))</span>
<a name="l00087"></a>00087 <span class="preprocessor"></span>
<a name="l00088"></a>00088 <span class="preprocessor">#if defined(APR_IS_DEV_VERSION) || defined(DOXYGEN)</span>
<a name="l00089"></a>00089 <span class="preprocessor"></span><span class="comment">/** Internal: string form of the &quot;is dev&quot; flag */</span>
<a name="l00090"></a><a class="code" href="apr__version_8h.html#aa07a7cfd506f536ca2e097d924ffcec8">00090</a> <span class="preprocessor">#define APR_IS_DEV_STRING &quot;-dev&quot;</span>
<a name="l00091"></a>00091 <span class="preprocessor"></span><span class="preprocessor">#else</span>
<a name="l00092"></a>00092 <span class="preprocessor"></span><span class="preprocessor">#define APR_IS_DEV_STRING &quot;&quot;</span>
<a name="l00093"></a>00093 <span class="preprocessor"></span><span class="preprocessor">#endif</span>
<a name="l00094"></a>00094 <span class="preprocessor"></span>
<a name="l00095"></a>00095 <span class="comment">/* APR_STRINGIFY is defined here, and also in apr_general.h, so wrap it */</span>
<a name="l00096"></a>00096 <span class="preprocessor">#ifndef APR_STRINGIFY</span>
<a name="l00097"></a>00097 <span class="preprocessor"></span><span class="comment">/** Properly quote a value as a string in the C preprocessor */</span>
<a name="l00098"></a><a class="code" href="apr__version_8h.html#ae90215615972dfa4108018304361ef0b">00098</a> <span class="preprocessor">#define APR_STRINGIFY(n) APR_STRINGIFY_HELPER(n)</span>
<a name="l00099"></a>00099 <span class="preprocessor"></span><span class="comment">/** Helper macro for APR_STRINGIFY */</span>
<a name="l00100"></a><a class="code" href="apr__version_8h.html#a71918dd8c53e093283b43b0ff0965439">00100</a> <span class="preprocessor">#define APR_STRINGIFY_HELPER(n) #n</span>
<a name="l00101"></a>00101 <span class="preprocessor"></span><span class="preprocessor">#endif</span>
<a name="l00102"></a>00102 <span class="preprocessor"></span><span class="comment"></span>
<a name="l00103"></a>00103 <span class="comment">/** The formatted string of APR&#39;s version */</span>
<a name="l00104"></a><a class="code" href="apr__version_8h.html#ac420a8c4636151e4086a18673a3335e7">00104</a> <span class="preprocessor">#define APR_VERSION_STRING \</span>
<a name="l00105"></a>00105 <span class="preprocessor">     APR_STRINGIFY(APR_MAJOR_VERSION) &quot;.&quot; \</span>
<a name="l00106"></a>00106 <span class="preprocessor">     APR_STRINGIFY(APR_MINOR_VERSION) &quot;.&quot; \</span>
<a name="l00107"></a>00107 <span class="preprocessor">     APR_STRINGIFY(APR_PATCH_VERSION) \</span>
<a name="l00108"></a>00108 <span class="preprocessor">     APR_IS_DEV_STRING</span>
<a name="l00109"></a>00109 <span class="preprocessor"></span><span class="comment"></span>
<a name="l00110"></a>00110 <span class="comment">/** An alternative formatted string of APR&#39;s version */</span>
<a name="l00111"></a>00111 <span class="comment">/* macro for Win32 .rc files using numeric csv representation */</span>
<a name="l00112"></a><a class="code" href="apr__version_8h.html#ac49895cc329e2b507f72a7afc62a25c6">00112</a> <span class="preprocessor">#define APR_VERSION_STRING_CSV APR_MAJOR_VERSION ##, \</span>
<a name="l00113"></a>00113 <span class="preprocessor">                             ##APR_MINOR_VERSION ##, \</span>
<a name="l00114"></a>00114 <span class="preprocessor">                             ##APR_PATCH_VERSION</span>
<a name="l00115"></a>00115 <span class="preprocessor"></span>
<a name="l00116"></a>00116 
<a name="l00117"></a>00117 <span class="preprocessor">#ifndef APR_VERSION_ONLY</span>
<a name="l00118"></a>00118 <span class="preprocessor"></span>
<a name="l00119"></a>00119 <span class="comment">/* The C language API to access the version at run time, </span>
<a name="l00120"></a>00120 <span class="comment"> * as opposed to compile time.  APR_VERSION_ONLY may be defined </span>
<a name="l00121"></a>00121 <span class="comment"> * externally when preprocessing apr_version.h to obtain strictly </span>
<a name="l00122"></a>00122 <span class="comment"> * the C Preprocessor macro declarations.</span>
<a name="l00123"></a>00123 <span class="comment"> */</span>
<a name="l00124"></a>00124 
<a name="l00125"></a>00125 <span class="preprocessor">#include &quot;<a class="code" href="apr_8h.html" title="APR Platform Definitions.">apr.h</a>&quot;</span>
<a name="l00126"></a>00126 
<a name="l00127"></a>00127 <span class="preprocessor">#ifdef __cplusplus</span>
<a name="l00128"></a>00128 <span class="preprocessor"></span><span class="keyword">extern</span> <span class="stringliteral">&quot;C&quot;</span> {
<a name="l00129"></a>00129 <span class="preprocessor">#endif</span>
<a name="l00130"></a>00130 <span class="preprocessor"></span><span class="comment"></span>
<a name="l00131"></a>00131 <span class="comment">/** </span>
<a name="l00132"></a>00132 <span class="comment"> * The numeric version information is broken out into fields within this </span>
<a name="l00133"></a>00133 <span class="comment"> * structure. </span>
<a name="l00134"></a>00134 <span class="comment"> */</span>
<a name="l00135"></a><a class="code" href="structapr__version__t.html">00135</a> <span class="keyword">typedef</span> <span class="keyword">struct </span>{
<a name="l00136"></a><a class="code" href="structapr__version__t.html#a0ae64fee85387834ab76d9f9288373ab">00136</a>     <span class="keywordtype">int</span> major;      <span class="comment">/**&lt; major number */</span>
<a name="l00137"></a><a class="code" href="structapr__version__t.html#aab0a1e8362517416389631bceeeedbad">00137</a>     <span class="keywordtype">int</span> minor;      <span class="comment">/**&lt; minor number */</span>
<a name="l00138"></a><a class="code" href="structapr__version__t.html#a98a629a88e776642d6e527d7535e0791">00138</a>     <span class="keywordtype">int</span> patch;      <span class="comment">/**&lt; patch number */</span>
<a name="l00139"></a><a class="code" href="structapr__version__t.html#aadc878af1010faa53e365e1142c81ced">00139</a>     <span class="keywordtype">int</span> is_dev;     <span class="comment">/**&lt; is development (1 or 0) */</span>
<a name="l00140"></a>00140 } <a class="code" href="structapr__version__t.html">apr_version_t</a>;
<a name="l00141"></a>00141 <span class="comment"></span>
<a name="l00142"></a>00142 <span class="comment">/**</span>
<a name="l00143"></a>00143 <span class="comment"> * Return APR&#39;s version information information in a numeric form.</span>
<a name="l00144"></a>00144 <span class="comment"> *</span>
<a name="l00145"></a>00145 <span class="comment"> *  @param pvsn Pointer to a version structure for returning the version</span>
<a name="l00146"></a>00146 <span class="comment"> *              information.</span>
<a name="l00147"></a>00147 <span class="comment"> */</span>
<a name="l00148"></a>00148 <a class="code" href="group__apr__platform.html#gad7b91b811a172bfa802603c2fb688f98">APR_DECLARE</a>(<span class="keywordtype">void</span>) <a class="code" href="apr__version_8h.html#a15d53cfd826fcab2749e3df90bdd5fcc">apr_version</a>(<a class="code" href="structapr__version__t.html">apr_version_t</a> *pvsn);
<a name="l00149"></a>00149 <span class="comment"></span>
<a name="l00150"></a>00150 <span class="comment">/** Return APR&#39;s version information as a string. */</span>
<a name="l00151"></a>00151 <a class="code" href="group__apr__platform.html#gad7b91b811a172bfa802603c2fb688f98">APR_DECLARE</a>(const <span class="keywordtype">char</span> *) <a class="code" href="apr__version_8h.html#af5ca08ef6ad70319d0e63f915e650768">apr_version_string</a>(<span class="keywordtype">void</span>);
<a name="l00152"></a>00152 
<a name="l00153"></a>00153 <span class="preprocessor">#ifdef __cplusplus</span>
<a name="l00154"></a>00154 <span class="preprocessor"></span>}
<a name="l00155"></a>00155 <span class="preprocessor">#endif</span>
<a name="l00156"></a>00156 <span class="preprocessor"></span>
<a name="l00157"></a>00157 <span class="preprocessor">#endif </span><span class="comment">/* ndef APR_VERSION_ONLY */</span>
<a name="l00158"></a>00158 
<a name="l00159"></a>00159 <span class="preprocessor">#endif </span><span class="comment">/* ndef APR_VERSION_H */</span>
</pre></div></div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Data Structures</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Defines</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<hr class="footer"/><address style="text-align: right;"><small>Generated on Mon May 23 21:31:32 2011 for Apache Portable Runtime by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.6.3 </small></address>
</body>
</html>
