<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<title>Apache Portable Runtime: apr_sockaddr_t Struct Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<!-- Generated by Doxygen 1.6.3 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul>
      <li><a href="index.html"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.html"><span>Related&nbsp;Pages</span></a></li>
      <li><a href="modules.html"><span>Modules</span></a></li>
      <li class="current"><a href="annotated.html"><span>Data&nbsp;Structures</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <img id="MSearchSelect" src="search/search.png"
             onmouseover="return searchBox.OnSearchSelectShow()"
             onmouseout="return searchBox.OnSearchSelectHide()"
             alt=""/>
        <input type="text" id="MSearchField" value="Search" accesskey="S"
             onfocus="searchBox.OnSearchFieldFocus(true)" 
             onblur="searchBox.OnSearchFieldFocus(false)" 
             onkeyup="searchBox.OnSearchFieldChange(event)"/>
        <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs">
    <ul>
      <li><a href="annotated.html"><span>Data&nbsp;Structures</span></a></li>
      <li><a href="functions.html"><span>Data&nbsp;Fields</span></a></li>
    </ul>
  </div>
</div>
<div class="contents">
<h1>apr_sockaddr_t Struct Reference<br/>
<small>
[<a class="el" href="group__apr__network__io.html">Network Routines</a>]</small>
</h1><!-- doxytag: class="apr_sockaddr_t" -->
<p><code>#include &lt;<a class="el" href="apr__network__io_8h_source.html">apr_network_io.h</a>&gt;</code></p>
<table border="0" cellpadding="0" cellspacing="0">
<tr><td colspan="2"><h2>Data Fields</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="group__apr__pools.html#gaf137f28edcf9a086cd6bc36c20d7cdfb">apr_pool_t</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="structapr__sockaddr__t.html#a5f2d72a6a181cf2f54ba7c922aa0dfab">pool</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">char *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="structapr__sockaddr__t.html#a8e675775b407f25674aaa938a40de9cd">hostname</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">char *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="structapr__sockaddr__t.html#a668335161a8347b9a34c600bff80b52f">servname</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="group__apr__network__io.html#gaa670a71960f6eb4fe0d0de2a1e7aba03">apr_port_t</a>&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="structapr__sockaddr__t.html#a174c19138de9c208f13ed71b5892e505">port</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">apr_int32_t&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="structapr__sockaddr__t.html#ac17f6e803928cfc29069a6e62dcb3a52">family</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">apr_socklen_t&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="structapr__sockaddr__t.html#aef1d2a482f85eeab7b6bf0a7732a087a">salen</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">int&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="structapr__sockaddr__t.html#a81be21b2eb968b83ca36183213c99867">ipaddr_len</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">int&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="structapr__sockaddr__t.html#a8f7cda5562e904a1398ed5a4a6f0a9d9">addr_str_len</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">void *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="structapr__sockaddr__t.html#a6e1b71121ada4047acde36c6777b5442">ipaddr_ptr</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="structapr__sockaddr__t.html">apr_sockaddr_t</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="structapr__sockaddr__t.html#a774835c6b8e3adf255b752e8b126c434">next</a></td></tr>
<tr><td class="memItemLeft" >union {</td></tr>
<tr><td class="memItemLeft" >&nbsp;&nbsp;&nbsp;struct sockaddr_in&nbsp;&nbsp;&nbsp;<a class="el" href="structapr__sockaddr__t.html#a7d5cf0290260c3c448360fc819b28714">sin</a></td></tr>
<tr><td class="memItemLeft" valign="top">}&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="structapr__sockaddr__t.html#a3ca40eae640100e0f157e7c21b33a17d">sa</a></td></tr>
</table>
<hr/><a name="_details"></a><h2>Detailed Description</h2>
<p>APRs socket address type, used to ensure protocol independence </p>
<hr/><h2>Field Documentation</h2>
<a class="anchor" id="a8f7cda5562e904a1398ed5a4a6f0a9d9"></a><!-- doxytag: member="apr_sockaddr_t::addr_str_len" ref="a8f7cda5562e904a1398ed5a4a6f0a9d9" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">int <a class="el" href="structapr__sockaddr__t.html#a8f7cda5562e904a1398ed5a4a6f0a9d9">apr_sockaddr_t::addr_str_len</a></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>How big should the address buffer be? 16 for v4 or 46 for v6 used in inet_ntop... </p>

</div>
</div>
<a class="anchor" id="ac17f6e803928cfc29069a6e62dcb3a52"></a><!-- doxytag: member="apr_sockaddr_t::family" ref="ac17f6e803928cfc29069a6e62dcb3a52" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">apr_int32_t <a class="el" href="structapr__sockaddr__t.html#ac17f6e803928cfc29069a6e62dcb3a52">apr_sockaddr_t::family</a></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>The family </p>

</div>
</div>
<a class="anchor" id="a8e675775b407f25674aaa938a40de9cd"></a><!-- doxytag: member="apr_sockaddr_t::hostname" ref="a8e675775b407f25674aaa938a40de9cd" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">char* <a class="el" href="structapr__sockaddr__t.html#a8e675775b407f25674aaa938a40de9cd">apr_sockaddr_t::hostname</a></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>The hostname </p>

</div>
</div>
<a class="anchor" id="a81be21b2eb968b83ca36183213c99867"></a><!-- doxytag: member="apr_sockaddr_t::ipaddr_len" ref="a81be21b2eb968b83ca36183213c99867" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">int <a class="el" href="structapr__sockaddr__t.html#a81be21b2eb968b83ca36183213c99867">apr_sockaddr_t::ipaddr_len</a></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>How big is the ip address structure we're using? </p>

</div>
</div>
<a class="anchor" id="a6e1b71121ada4047acde36c6777b5442"></a><!-- doxytag: member="apr_sockaddr_t::ipaddr_ptr" ref="a6e1b71121ada4047acde36c6777b5442" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void* <a class="el" href="structapr__sockaddr__t.html#a6e1b71121ada4047acde36c6777b5442">apr_sockaddr_t::ipaddr_ptr</a></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>This points to the IP address structure within the appropriate sockaddr structure. </p>

</div>
</div>
<a class="anchor" id="a774835c6b8e3adf255b752e8b126c434"></a><!-- doxytag: member="apr_sockaddr_t::next" ref="a774835c6b8e3adf255b752e8b126c434" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="structapr__sockaddr__t.html">apr_sockaddr_t</a>* <a class="el" href="structapr__sockaddr__t.html#a774835c6b8e3adf255b752e8b126c434">apr_sockaddr_t::next</a></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>If multiple addresses were found by <a class="el" href="group__apr__network__io.html#gaa2f399ca2b60b35c0abf7630298c6c9f">apr_sockaddr_info_get()</a>, this points to a representation of the next address. </p>

</div>
</div>
<a class="anchor" id="a5f2d72a6a181cf2f54ba7c922aa0dfab"></a><!-- doxytag: member="apr_sockaddr_t::pool" ref="a5f2d72a6a181cf2f54ba7c922aa0dfab" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="group__apr__pools.html#gaf137f28edcf9a086cd6bc36c20d7cdfb">apr_pool_t</a>* <a class="el" href="structapr__sockaddr__t.html#a5f2d72a6a181cf2f54ba7c922aa0dfab">apr_sockaddr_t::pool</a></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>The pool to use... </p>

</div>
</div>
<a class="anchor" id="a174c19138de9c208f13ed71b5892e505"></a><!-- doxytag: member="apr_sockaddr_t::port" ref="a174c19138de9c208f13ed71b5892e505" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="group__apr__network__io.html#gaa670a71960f6eb4fe0d0de2a1e7aba03">apr_port_t</a> <a class="el" href="structapr__sockaddr__t.html#a174c19138de9c208f13ed71b5892e505">apr_sockaddr_t::port</a></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>The numeric port </p>

</div>
</div>
<a class="anchor" id="a3ca40eae640100e0f157e7c21b33a17d"></a><!-- doxytag: member="apr_sockaddr_t::sa" ref="a3ca40eae640100e0f157e7c21b33a17d" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">union { ... }   <a class="el" href="structapr__sockaddr__t.html#a3ca40eae640100e0f157e7c21b33a17d">apr_sockaddr_t::sa</a></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>Union of either IPv4 or IPv6 sockaddr. </p>

</div>
</div>
<a class="anchor" id="aef1d2a482f85eeab7b6bf0a7732a087a"></a><!-- doxytag: member="apr_sockaddr_t::salen" ref="aef1d2a482f85eeab7b6bf0a7732a087a" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">apr_socklen_t <a class="el" href="structapr__sockaddr__t.html#aef1d2a482f85eeab7b6bf0a7732a087a">apr_sockaddr_t::salen</a></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>How big is the sockaddr we're using? </p>

</div>
</div>
<a class="anchor" id="a668335161a8347b9a34c600bff80b52f"></a><!-- doxytag: member="apr_sockaddr_t::servname" ref="a668335161a8347b9a34c600bff80b52f" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">char* <a class="el" href="structapr__sockaddr__t.html#a668335161a8347b9a34c600bff80b52f">apr_sockaddr_t::servname</a></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>Either a string of the port number or the service name for the port </p>

</div>
</div>
<a class="anchor" id="a7d5cf0290260c3c448360fc819b28714"></a><!-- doxytag: member="apr_sockaddr_t::sin" ref="a7d5cf0290260c3c448360fc819b28714" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">struct sockaddr_in <a class="el" href="structapr__sockaddr__t.html#a7d5cf0290260c3c448360fc819b28714">apr_sockaddr_t::sin</a></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>IPv4 sockaddr structure </p>

</div>
</div>
<hr/>The documentation for this struct was generated from the following file:<ul>
<li><a class="el" href="apr__network__io_8h_source.html">apr_network_io.h</a></li>
</ul>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Data Structures</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Defines</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<hr class="footer"/><address style="text-align: right;"><small>Generated on Mon May 23 21:31:33 2011 for Apache Portable Runtime by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.6.3 </small></address>
</body>
</html>
