<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<title>Apache Portable Runtime: apr_fnmatch.h Source File</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<!-- Generated by Doxygen 1.6.3 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul>
      <li><a href="index.html"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.html"><span>Related&nbsp;Pages</span></a></li>
      <li><a href="modules.html"><span>Modules</span></a></li>
      <li><a href="annotated.html"><span>Data&nbsp;Structures</span></a></li>
      <li class="current"><a href="files.html"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <img id="MSearchSelect" src="search/search.png"
             onmouseover="return searchBox.OnSearchSelectShow()"
             onmouseout="return searchBox.OnSearchSelectHide()"
             alt=""/>
        <input type="text" id="MSearchField" value="Search" accesskey="S"
             onfocus="searchBox.OnSearchFieldFocus(true)" 
             onblur="searchBox.OnSearchFieldFocus(false)" 
             onkeyup="searchBox.OnSearchFieldChange(event)"/>
        <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs">
    <ul>
      <li><a href="files.html"><span>File&nbsp;List</span></a></li>
      <li><a href="globals.html"><span>Globals</span></a></li>
    </ul>
  </div>
<h1>apr_fnmatch.h</h1><a href="apr__fnmatch_8h.html">Go to the documentation of this file.</a><div class="fragment"><pre class="fragment"><a name="l00001"></a>00001 <span class="comment">/*</span>
<a name="l00002"></a>00002 <span class="comment"> * Copyright (c) 1992, 1993</span>
<a name="l00003"></a>00003 <span class="comment"> *      The Regents of the University of California.  All rights reserved.</span>
<a name="l00004"></a>00004 <span class="comment"> *</span>
<a name="l00005"></a>00005 <span class="comment"> * Redistribution and use in source and binary forms, with or without</span>
<a name="l00006"></a>00006 <span class="comment"> * modification, are permitted provided that the following conditions</span>
<a name="l00007"></a>00007 <span class="comment"> * are met:</span>
<a name="l00008"></a>00008 <span class="comment"> * 1. Redistributions of source code must retain the above copyright</span>
<a name="l00009"></a>00009 <span class="comment"> *    notice, this list of conditions and the following disclaimer.</span>
<a name="l00010"></a>00010 <span class="comment"> * 2. Redistributions in binary form must reproduce the above copyright</span>
<a name="l00011"></a>00011 <span class="comment"> *    notice, this list of conditions and the following disclaimer in the</span>
<a name="l00012"></a>00012 <span class="comment"> *    documentation and/or other materials provided with the distribution.</span>
<a name="l00013"></a>00013 <span class="comment"> * 3. All advertising materials mentioning features or use of this software</span>
<a name="l00014"></a>00014 <span class="comment"> *    must display the following acknowledgement:</span>
<a name="l00015"></a>00015 <span class="comment"> *      This product includes software developed by the University of</span>
<a name="l00016"></a>00016 <span class="comment"> *      California, Berkeley and its contributors.</span>
<a name="l00017"></a>00017 <span class="comment"> * 4. Neither the name of the University nor the names of its contributors</span>
<a name="l00018"></a>00018 <span class="comment"> *    may be used to endorse or promote products derived from this software</span>
<a name="l00019"></a>00019 <span class="comment"> *    without specific prior written permission.</span>
<a name="l00020"></a>00020 <span class="comment"> *</span>
<a name="l00021"></a>00021 <span class="comment"> * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS&#39;&#39; AND</span>
<a name="l00022"></a>00022 <span class="comment"> * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE</span>
<a name="l00023"></a>00023 <span class="comment"> * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE</span>
<a name="l00024"></a>00024 <span class="comment"> * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE</span>
<a name="l00025"></a>00025 <span class="comment"> * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL</span>
<a name="l00026"></a>00026 <span class="comment"> * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS</span>
<a name="l00027"></a>00027 <span class="comment"> * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)</span>
<a name="l00028"></a>00028 <span class="comment"> * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT</span>
<a name="l00029"></a>00029 <span class="comment"> * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY</span>
<a name="l00030"></a>00030 <span class="comment"> * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF</span>
<a name="l00031"></a>00031 <span class="comment"> * SUCH DAMAGE.</span>
<a name="l00032"></a>00032 <span class="comment"> *</span>
<a name="l00033"></a>00033 <span class="comment"> *      @(#)fnmatch.h   8.1 (Berkeley) 6/2/93</span>
<a name="l00034"></a>00034 <span class="comment"> */</span>
<a name="l00035"></a>00035 
<a name="l00036"></a>00036 <span class="comment">/* This file has been modified by the Apache Software Foundation. */</span>
<a name="l00037"></a>00037 <span class="preprocessor">#ifndef _APR_FNMATCH_H_</span>
<a name="l00038"></a>00038 <span class="preprocessor"></span><span class="preprocessor">#define _APR_FNMATCH_H_</span>
<a name="l00039"></a>00039 <span class="preprocessor"></span><span class="comment"></span>
<a name="l00040"></a>00040 <span class="comment">/**</span>
<a name="l00041"></a>00041 <span class="comment"> * @file apr_fnmatch.h</span>
<a name="l00042"></a>00042 <span class="comment"> * @brief APR FNMatch Functions</span>
<a name="l00043"></a>00043 <span class="comment"> */</span>
<a name="l00044"></a>00044 
<a name="l00045"></a>00045 <span class="preprocessor">#include &quot;<a class="code" href="apr__errno_8h.html" title="APR Error Codes.">apr_errno.h</a>&quot;</span>
<a name="l00046"></a>00046 <span class="preprocessor">#include &quot;<a class="code" href="apr__tables_8h.html" title="APR Table library.">apr_tables.h</a>&quot;</span>
<a name="l00047"></a>00047 
<a name="l00048"></a>00048 <span class="preprocessor">#ifdef __cplusplus</span>
<a name="l00049"></a>00049 <span class="preprocessor"></span><span class="keyword">extern</span> <span class="stringliteral">&quot;C&quot;</span> {
<a name="l00050"></a>00050 <span class="preprocessor">#endif</span>
<a name="l00051"></a>00051 <span class="preprocessor"></span><span class="comment"></span>
<a name="l00052"></a>00052 <span class="comment">/**</span>
<a name="l00053"></a>00053 <span class="comment"> * @defgroup apr_fnmatch Filename Matching Functions</span>
<a name="l00054"></a>00054 <span class="comment"> * @ingroup APR </span>
<a name="l00055"></a>00055 <span class="comment"> * @{</span>
<a name="l00056"></a>00056 <span class="comment"> */</span>
<a name="l00057"></a>00057 
<a name="l00058"></a><a class="code" href="group__apr__fnmatch.html#gaea769621807400e4c741e7deddf6c3df">00058</a> <span class="preprocessor">#define APR_FNM_NOMATCH     1     </span><span class="comment">/**&lt; Match failed. */</span>
<a name="l00059"></a>00059  
<a name="l00060"></a><a class="code" href="group__apr__fnmatch.html#gae12c1286631f316647be6dc007170630">00060</a> <span class="preprocessor">#define APR_FNM_NOESCAPE    0x01  </span><span class="comment">/**&lt; Disable backslash escaping. */</span>
<a name="l00061"></a><a class="code" href="group__apr__fnmatch.html#ga0d421a2cef68cb590f958b5de6c7fe1b">00061</a> <span class="preprocessor">#define APR_FNM_PATHNAME    0x02  </span><span class="comment">/**&lt; Slash must be matched by slash. */</span>
<a name="l00062"></a><a class="code" href="group__apr__fnmatch.html#ga4806f936b6eacc59dfed831d67b750ef">00062</a> <span class="preprocessor">#define APR_FNM_PERIOD      0x04  </span><span class="comment">/**&lt; Period must be matched by period. */</span>
<a name="l00063"></a><a class="code" href="group__apr__fnmatch.html#ga5cee1c0a917a283a193721d11160b502">00063</a> <span class="preprocessor">#define APR_FNM_CASE_BLIND  0x08  </span><span class="comment">/**&lt; Compare characters case-insensitively.</span>
<a name="l00064"></a>00064 <span class="comment">                                   * @remark This flag is an Apache addition </span>
<a name="l00065"></a>00065 <span class="comment">                                   */</span>
<a name="l00066"></a>00066 <span class="comment"></span>
<a name="l00067"></a>00067 <span class="comment">/**</span>
<a name="l00068"></a>00068 <span class="comment"> * Try to match the string to the given pattern, return APR_SUCCESS if</span>
<a name="l00069"></a>00069 <span class="comment"> *    match, else return APR_FNM_NOMATCH.  Note that there is no such thing as</span>
<a name="l00070"></a>00070 <span class="comment"> *    an illegal pattern.</span>
<a name="l00071"></a>00071 <span class="comment"> *</span>
<a name="l00072"></a>00072 <span class="comment"> * With all flags unset, a pattern is interpreted as such:</span>
<a name="l00073"></a>00073 <span class="comment"> *</span>
<a name="l00074"></a>00074 <span class="comment"> * PATTERN: Backslash followed by any character, including another</span>
<a name="l00075"></a>00075 <span class="comment"> *          backslash.&lt;br/&gt;</span>
<a name="l00076"></a>00076 <span class="comment"> * MATCHES: That character exactly.</span>
<a name="l00077"></a>00077 <span class="comment"> * </span>
<a name="l00078"></a>00078 <span class="comment"> * &lt;p&gt;</span>
<a name="l00079"></a>00079 <span class="comment"> * PATTERN: ?&lt;br/&gt;</span>
<a name="l00080"></a>00080 <span class="comment"> * MATCHES: Any single character.</span>
<a name="l00081"></a>00081 <span class="comment"> * &lt;/p&gt;</span>
<a name="l00082"></a>00082 <span class="comment"> * </span>
<a name="l00083"></a>00083 <span class="comment"> * &lt;p&gt;</span>
<a name="l00084"></a>00084 <span class="comment"> * PATTERN: *&lt;br/&gt;</span>
<a name="l00085"></a>00085 <span class="comment"> * MATCHES: Any sequence of zero or more characters. (Note that multiple</span>
<a name="l00086"></a>00086 <span class="comment"> *          *s in a row are equivalent to one.)</span>
<a name="l00087"></a>00087 <span class="comment"> * </span>
<a name="l00088"></a>00088 <span class="comment"> * PATTERN: Any character other than \?*[ or a \ at the end of the pattern&lt;br/&gt;</span>
<a name="l00089"></a>00089 <span class="comment"> * MATCHES: That character exactly. (Case sensitive.)</span>
<a name="l00090"></a>00090 <span class="comment"> * </span>
<a name="l00091"></a>00091 <span class="comment"> * PATTERN: [ followed by a class description followed by ]&lt;br/&gt;</span>
<a name="l00092"></a>00092 <span class="comment"> * MATCHES: A single character described by the class description.</span>
<a name="l00093"></a>00093 <span class="comment"> *          (Never matches, if the class description reaches until the</span>
<a name="l00094"></a>00094 <span class="comment"> *          end of the string without a ].) If the first character of</span>
<a name="l00095"></a>00095 <span class="comment"> *          the class description is ^ or !, the sense of the description</span>
<a name="l00096"></a>00096 <span class="comment"> *          is reversed.  The rest of the class description is a list of</span>
<a name="l00097"></a>00097 <span class="comment"> *          single characters or pairs of characters separated by -. Any</span>
<a name="l00098"></a>00098 <span class="comment"> *          of those characters can have a backslash in front of them,</span>
<a name="l00099"></a>00099 <span class="comment"> *          which is ignored; this lets you use the characters ] and -</span>
<a name="l00100"></a>00100 <span class="comment"> *          in the character class, as well as ^ and ! at the</span>
<a name="l00101"></a>00101 <span class="comment"> *          beginning.  The pattern matches a single character if it</span>
<a name="l00102"></a>00102 <span class="comment"> *          is one of the listed characters or falls into one of the</span>
<a name="l00103"></a>00103 <span class="comment"> *          listed ranges (inclusive, case sensitive).  Ranges with</span>
<a name="l00104"></a>00104 <span class="comment"> *          the first character larger than the second are legal but</span>
<a name="l00105"></a>00105 <span class="comment"> *          never match. Edge cases: [] never matches, and [^] and [!]</span>
<a name="l00106"></a>00106 <span class="comment"> *          always match without consuming a character.</span>
<a name="l00107"></a>00107 <span class="comment"> * </span>
<a name="l00108"></a>00108 <span class="comment"> * Note that these patterns attempt to match the entire string, not</span>
<a name="l00109"></a>00109 <span class="comment"> * just find a substring matching the pattern.</span>
<a name="l00110"></a>00110 <span class="comment"> *</span>
<a name="l00111"></a>00111 <span class="comment"> * @param pattern The pattern to match to</span>
<a name="l00112"></a>00112 <span class="comment"> * @param strings The string we are trying to match</span>
<a name="l00113"></a>00113 <span class="comment"> * @param flags flags to use in the match.  Bitwise OR of:</span>
<a name="l00114"></a>00114 <span class="comment"> * &lt;pre&gt;</span>
<a name="l00115"></a>00115 <span class="comment"> *              APR_FNM_NOESCAPE       Disable backslash escaping</span>
<a name="l00116"></a>00116 <span class="comment"> *              APR_FNM_PATHNAME       Slash must be matched by slash</span>
<a name="l00117"></a>00117 <span class="comment"> *              APR_FNM_PERIOD         Period must be matched by period</span>
<a name="l00118"></a>00118 <span class="comment"> *              APR_FNM_CASE_BLIND     Compare characters case-insensitively.</span>
<a name="l00119"></a>00119 <span class="comment"> * &lt;/pre&gt;</span>
<a name="l00120"></a>00120 <span class="comment"> */</span>
<a name="l00121"></a>00121 
<a name="l00122"></a>00122 <a class="code" href="group__apr__platform.html#gad7b91b811a172bfa802603c2fb688f98">APR_DECLARE</a>(<a class="code" href="group__apr__errno.html#gaf76ee4543247e9fb3f3546203e590a6c">apr_status_t</a>) <a class="code" href="group__apr__fnmatch.html#gabe9c7d7efe6afc203a01befbc45bad96">apr_fnmatch</a>(const <span class="keywordtype">char</span> *pattern, 
<a name="l00123"></a>00123                                       const <span class="keywordtype">char</span> *strings, <span class="keywordtype">int</span> flags);
<a name="l00124"></a>00124 <span class="comment"></span>
<a name="l00125"></a>00125 <span class="comment">/**</span>
<a name="l00126"></a>00126 <span class="comment"> * Determine if the given pattern is a regular expression.</span>
<a name="l00127"></a>00127 <span class="comment"> * @param pattern The pattern to search for glob characters.</span>
<a name="l00128"></a>00128 <span class="comment"> * @return non-zero if pattern has any glob characters in it</span>
<a name="l00129"></a>00129 <span class="comment"> */</span>
<a name="l00130"></a>00130 <a class="code" href="group__apr__platform.html#gad7b91b811a172bfa802603c2fb688f98">APR_DECLARE</a>(<span class="keywordtype">int</span>) <a class="code" href="group__apr__fnmatch.html#ga4e7828bb7be756d999f13b8af8202204">apr_fnmatch_test</a>(const <span class="keywordtype">char</span> *pattern);
<a name="l00131"></a>00131 <span class="comment"></span>
<a name="l00132"></a>00132 <span class="comment">/**</span>
<a name="l00133"></a>00133 <span class="comment"> * Find all files that match a specified pattern.</span>
<a name="l00134"></a>00134 <span class="comment"> * @param pattern The pattern to use for finding files.</span>
<a name="l00135"></a>00135 <span class="comment"> * @param result Array to use when storing the results</span>
<a name="l00136"></a>00136 <span class="comment"> * @param p The pool to use.</span>
<a name="l00137"></a>00137 <span class="comment"> * @return non-zero if pattern has any glob characters in it</span>
<a name="l00138"></a>00138 <span class="comment"> */</span>
<a name="l00139"></a>00139 <a class="code" href="group__apr__platform.html#gad7b91b811a172bfa802603c2fb688f98">APR_DECLARE</a>(<a class="code" href="group__apr__errno.html#gaf76ee4543247e9fb3f3546203e590a6c">apr_status_t</a>) <a class="code" href="group__apr__fnmatch.html#gaba55810d3e241b61b9f47f23231e3a02">apr_match_glob</a>(const <span class="keywordtype">char</span> *pattern, 
<a name="l00140"></a>00140                                          <a class="code" href="structapr__array__header__t.html">apr_array_header_t</a> **result,
<a name="l00141"></a>00141                                          <a class="code" href="group__apr__pools.html#gaf137f28edcf9a086cd6bc36c20d7cdfb">apr_pool_t</a> *p);
<a name="l00142"></a>00142 <span class="comment"></span>
<a name="l00143"></a>00143 <span class="comment">/** @} */</span>
<a name="l00144"></a>00144 
<a name="l00145"></a>00145 <span class="preprocessor">#ifdef __cplusplus</span>
<a name="l00146"></a>00146 <span class="preprocessor"></span>}
<a name="l00147"></a>00147 <span class="preprocessor">#endif</span>
<a name="l00148"></a>00148 <span class="preprocessor"></span>
<a name="l00149"></a>00149 <span class="preprocessor">#endif </span><span class="comment">/* !_APR_FNMATCH_H_ */</span>
</pre></div></div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Data Structures</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Defines</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<hr class="footer"/><address style="text-align: right;"><small>Generated on Mon May 23 21:31:31 2011 for Apache Portable Runtime by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.6.3 </small></address>
</body>
</html>
