<!-- This comment will put IE 6, 7 and 8 in quirks mode -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<title>Apache Portable Runtime: Thread portability Routines</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javaScript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
</head>
<body onload='searchBox.OnSelectItem(0);'>
<!-- Generated by Doxygen 1.6.3 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul>
      <li><a href="index.html"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.html"><span>Related&nbsp;Pages</span></a></li>
      <li><a href="modules.html"><span>Modules</span></a></li>
      <li><a href="annotated.html"><span>Data&nbsp;Structures</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <img id="MSearchSelect" src="search/search.png"
             onmouseover="return searchBox.OnSearchSelectShow()"
             onmouseout="return searchBox.OnSearchSelectHide()"
             alt=""/>
        <input type="text" id="MSearchField" value="Search" accesskey="S"
             onfocus="searchBox.OnSearchFieldFocus(true)" 
             onblur="searchBox.OnSearchFieldFocus(false)" 
             onkeyup="searchBox.OnSearchFieldChange(event)"/>
        <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
        </div>
      </li>
    </ul>
  </div>
</div>
<div class="contents">
<h1>Thread portability Routines<br/>
<small>
[<a class="el" href="group__apr__portabile.html">Portability Routines</a>]</small>
</h1><table border="0" cellpadding="0" cellspacing="0">
<tr><td colspan="2"><h2>Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="group__apr__errno.html#gaf76ee4543247e9fb3f3546203e590a6c">apr_status_t</a>&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="group__apr__os__thread.html#gadda5e99fc387491a2a9436bf6144bd49">apr_os_thread_get</a> (apr_os_thread_t **thethd, <a class="el" href="group__apr__thread__proc.html#ga646c71351e723d84f8cc8c8d1d5937be">apr_thread_t</a> *thd)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="group__apr__errno.html#gaf76ee4543247e9fb3f3546203e590a6c">apr_status_t</a>&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="group__apr__os__thread.html#ga2fd6ec9d398c4f2564765866c3d31219">apr_os_threadkey_get</a> (apr_os_threadkey_t *thekey, <a class="el" href="group__apr__thread__proc.html#ga337c9c1bd2d47740022071a5c41f2edb">apr_threadkey_t</a> *key)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="group__apr__errno.html#gaf76ee4543247e9fb3f3546203e590a6c">apr_status_t</a>&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="group__apr__os__thread.html#ga7eda58df34fbc11cd251899e575a1b0f">apr_os_thread_put</a> (<a class="el" href="group__apr__thread__proc.html#ga646c71351e723d84f8cc8c8d1d5937be">apr_thread_t</a> **thd, apr_os_thread_t *thethd, <a class="el" href="group__apr__pools.html#gaf137f28edcf9a086cd6bc36c20d7cdfb">apr_pool_t</a> *cont)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="group__apr__errno.html#gaf76ee4543247e9fb3f3546203e590a6c">apr_status_t</a>&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="group__apr__os__thread.html#ga386f6e3e205d422f623132bb50147133">apr_os_threadkey_put</a> (<a class="el" href="group__apr__thread__proc.html#ga337c9c1bd2d47740022071a5c41f2edb">apr_threadkey_t</a> **key, apr_os_threadkey_t *thekey, <a class="el" href="group__apr__pools.html#gaf137f28edcf9a086cd6bc36c20d7cdfb">apr_pool_t</a> *cont)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top">apr_os_thread_t&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="group__apr__os__thread.html#ga669a17c3a41db20bbc41c06d0e8881b3">apr_os_thread_current</a> (void)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top">int&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="group__apr__os__thread.html#gac55d4bbc219435046872b1236feb9bfa">apr_os_thread_equal</a> (apr_os_thread_t tid1, apr_os_thread_t tid2)</td></tr>
</table>
<hr/><h2>Function Documentation</h2>
<a class="anchor" id="ga669a17c3a41db20bbc41c06d0e8881b3"></a><!-- doxytag: member="apr_portable.h::apr_os_thread_current" ref="ga669a17c3a41db20bbc41c06d0e8881b3" args="(void)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">apr_os_thread_t apr_os_thread_current </td>
          <td>(</td>
          <td class="paramtype">void&nbsp;</td>
          <td class="paramname"></td>
          <td>&nbsp;)&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>Get the thread ID </p>

</div>
</div>
<a class="anchor" id="gac55d4bbc219435046872b1236feb9bfa"></a><!-- doxytag: member="apr_portable.h::apr_os_thread_equal" ref="gac55d4bbc219435046872b1236feb9bfa" args="(apr_os_thread_t tid1, apr_os_thread_t tid2)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">int apr_os_thread_equal </td>
          <td>(</td>
          <td class="paramtype">apr_os_thread_t&nbsp;</td>
          <td class="paramname"> <em>tid1</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">apr_os_thread_t&nbsp;</td>
          <td class="paramname"> <em>tid2</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>Compare two thread id's </p>
<dl><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign="top"></td><td valign="top"><em>tid1</em>&nbsp;</td><td>1st Thread ID to compare </td></tr>
    <tr><td valign="top"></td><td valign="top"><em>tid2</em>&nbsp;</td><td>2nd Thread ID to compare </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="gadda5e99fc387491a2a9436bf6144bd49"></a><!-- doxytag: member="apr_portable.h::apr_os_thread_get" ref="gadda5e99fc387491a2a9436bf6144bd49" args="(apr_os_thread_t **thethd, apr_thread_t *thd)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="group__apr__errno.html#gaf76ee4543247e9fb3f3546203e590a6c">apr_status_t</a> apr_os_thread_get </td>
          <td>(</td>
          <td class="paramtype">apr_os_thread_t **&nbsp;</td>
          <td class="paramname"> <em>thethd</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="group__apr__thread__proc.html#ga646c71351e723d84f8cc8c8d1d5937be">apr_thread_t</a> *&nbsp;</td>
          <td class="paramname"> <em>thd</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>convert the thread to os specific type from apr type. </p>
<dl><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign="top"></td><td valign="top"><em>thethd</em>&nbsp;</td><td>The apr thread to convert </td></tr>
    <tr><td valign="top"></td><td valign="top"><em>thd</em>&nbsp;</td><td>The os specific thread we are converting to </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ga7eda58df34fbc11cd251899e575a1b0f"></a><!-- doxytag: member="apr_portable.h::apr_os_thread_put" ref="ga7eda58df34fbc11cd251899e575a1b0f" args="(apr_thread_t **thd, apr_os_thread_t *thethd, apr_pool_t *cont)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="group__apr__errno.html#gaf76ee4543247e9fb3f3546203e590a6c">apr_status_t</a> apr_os_thread_put </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="group__apr__thread__proc.html#ga646c71351e723d84f8cc8c8d1d5937be">apr_thread_t</a> **&nbsp;</td>
          <td class="paramname"> <em>thd</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">apr_os_thread_t *&nbsp;</td>
          <td class="paramname"> <em>thethd</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="group__apr__pools.html#gaf137f28edcf9a086cd6bc36c20d7cdfb">apr_pool_t</a> *&nbsp;</td>
          <td class="paramname"> <em>cont</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>convert the thread from os specific type to apr type. </p>
<dl><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign="top"></td><td valign="top"><em>thd</em>&nbsp;</td><td>The apr thread we are converting to. </td></tr>
    <tr><td valign="top"></td><td valign="top"><em>thethd</em>&nbsp;</td><td>The os specific thread to convert </td></tr>
    <tr><td valign="top"></td><td valign="top"><em>cont</em>&nbsp;</td><td>The pool to use if it is needed. </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ga2fd6ec9d398c4f2564765866c3d31219"></a><!-- doxytag: member="apr_portable.h::apr_os_threadkey_get" ref="ga2fd6ec9d398c4f2564765866c3d31219" args="(apr_os_threadkey_t *thekey, apr_threadkey_t *key)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="group__apr__errno.html#gaf76ee4543247e9fb3f3546203e590a6c">apr_status_t</a> apr_os_threadkey_get </td>
          <td>(</td>
          <td class="paramtype">apr_os_threadkey_t *&nbsp;</td>
          <td class="paramname"> <em>thekey</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="group__apr__thread__proc.html#ga337c9c1bd2d47740022071a5c41f2edb">apr_threadkey_t</a> *&nbsp;</td>
          <td class="paramname"> <em>key</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>convert the thread private memory key to os specific type from an apr type. </p>
<dl><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign="top"></td><td valign="top"><em>thekey</em>&nbsp;</td><td>The apr handle we are converting from. </td></tr>
    <tr><td valign="top"></td><td valign="top"><em>key</em>&nbsp;</td><td>The os specific handle we are converting to. </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="ga386f6e3e205d422f623132bb50147133"></a><!-- doxytag: member="apr_portable.h::apr_os_threadkey_put" ref="ga386f6e3e205d422f623132bb50147133" args="(apr_threadkey_t **key, apr_os_threadkey_t *thekey, apr_pool_t *cont)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="group__apr__errno.html#gaf76ee4543247e9fb3f3546203e590a6c">apr_status_t</a> apr_os_threadkey_put </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="group__apr__thread__proc.html#ga337c9c1bd2d47740022071a5c41f2edb">apr_threadkey_t</a> **&nbsp;</td>
          <td class="paramname"> <em>key</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">apr_os_threadkey_t *&nbsp;</td>
          <td class="paramname"> <em>thekey</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="group__apr__pools.html#gaf137f28edcf9a086cd6bc36c20d7cdfb">apr_pool_t</a> *&nbsp;</td>
          <td class="paramname"> <em>cont</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">
<p>convert the thread private memory key from os specific type to apr type. </p>
<dl><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign="top"></td><td valign="top"><em>key</em>&nbsp;</td><td>The apr handle we are converting to. </td></tr>
    <tr><td valign="top"></td><td valign="top"><em>thekey</em>&nbsp;</td><td>The os specific handle to convert </td></tr>
    <tr><td valign="top"></td><td valign="top"><em>cont</em>&nbsp;</td><td>The pool to use if it is needed. </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
</div>
<!--- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&nbsp;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&nbsp;</span>Data Structures</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&nbsp;</span>Defines</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<hr class="footer"/><address style="text-align: right;"><small>Generated on Mon May 23 21:31:32 2011 for Apache Portable Runtime by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.6.3 </small></address>
</body>
</html>
